### PR TITLE
refactor: Rework AdwFlap

### PR DESCRIPTION
**Pull request by simrat39**
To Do:

- [x]  Fix overflow
- [x] Example
- [x] AdwFlapController

### CODE REVIEW

**Comment by simrat39** [comment]
libadwsidestack

**Comment by prateekmedia** [comment]
The Flap widget also acts as a drawer on small screens so user can either swipe to reveal the Flap or click on a button to reveal it as a drawer.

I dont know how it will be implemented.

**Comment by simrat39** [comment]
@prateekmedia we probably need something like AdwApp which takes in a headerbar and a sidebar, then we can hook into it and add a button / slide gesture

**Comment by simrat39** [comment]
libadwsidestack

Updated version:

- Added an animation on page change
- Fix the overflows
- Added an example

**Comment by simrat39** [comment]
The animation isn't a perfect copy, but this is the closest I could get it to. I don't know how to squish a widget vertically while keeping it aligned to the top.

**Comment by simrat39** [comment]
> The animation isn't a perfect copy, but this is the closest I could get it to. I don't know how to squish a widget vertically while keeping it aligned to the top.

nvm i got it :)

**Comment by simrat39** [comment]
Ok I think this is mostly done, atleast the desktop part.
A few things to think about:

1. Should we delegate the animated_indexed_stack stuff to the users?
2. Should the animation be customizable? (duration, curve etc)

**Pull request merged**
