### PR TITLE
Use cross fade animation for stack

### PR DESCRIPTION
**Pull request by MalcolmMielle**
Stack in adwaita use [crossfade animation](https://gnome.pages.gitlab.gnome.org/libadwaita/doc/1.0.0.alpha.3/class.ViewStack.html). This commit changes just that.

### CODE REVIEW

**Comment by prateekmedia** [comment]
LGTM, Thanks!

**Comment by prateekmedia** [comment]
Upon closer look I think we need that animation in one form or the other.

**Comment by MalcolmMielle** [comment]
What do you mean ?

**Comment by prateekmedia** [comment]
You should checkout Patterns app(based on libadwaita), It has the same
animations by default as the one you just removed.

Idk if they are using view stack or any other widget to get the animations.

Also the flap example in libadwaita demo has different animations when
another tab is clicked.

Also, are you on telegram? If yes, what's your username, sim and I have
created a telegram group to discuss regarding this organisation.

**Comment by MalcolmMielle** [comment]
I use libadwaita Demo has a model with libadwaita documentation :/. I'm kinda surprised at the animation not being cross-fading, since that's what described in the documentation (unless I'm mistaken ?). On my machine, libadwaita demo has no animation between any tab, hahaha.

I'll email you for telegram.

**Comment by prateekmedia** [comment]
@MalcolmMielle Yes, Normal adwaita-demo doesn't have it, you will find it in Patterns app(based on libadwaita).

**Pull request merged**
