### PR TITLE
feat: Introduce AdwScaffold and rework flap again

### PR DESCRIPTION
**Pull request by simrat39**
Show a drawer when modal

### CODE REVIEW

**Comment by simrat39** [comment]
This is very spaghetti code, please do not merge this right now. I can't think of a better way to do this, but it atleast works. I don't like making the user set the onDrawerChanged and friends

**Comment by simrat39** [comment]
Proposal: Add AdwScaffold which accepts a child and a drawer. We check if the child is the type AdwFlap, if it is we initialize a flapController, set the drawer gesture callbacks and everything is good then.

**Comment by simrat39** [comment]
https://user-images.githubusercontent.com/37233846/143667019-b4aac90f-16cd-44da-ae4c-3e50b40e4072.mp4

**Comment by prateekmedia** [comment]
Thanks for your amazing work, One thing that would make it even good is to show the draw over the content only and not over the headerbar, as this will hide access to close minimize etc buttons.

**Comment by simrat39** [comment]
image

Done

**Pull request merged**
