### PR TITLE
Removing dart from the super-linter.

### PR DESCRIPTION
**Pull request by MalcolmMielle**

### CODE REVIEW

**Comment by prateekmedia** [comment]
I think `flutter pub get` would not work as flutter is not installed in lint ci, Why not just add super linter to the ci.yml and not build the app at all, I think `flutter analyze` is enough and building is not necessary. I am open for opinions.

**Comment by MalcolmMielle** [comment]
That's exactly what I just did! Agreed 100%.

I removed dart from the super-linter so it will lint everything else. `CI.yml` already does the `analyze`.
And I found why the previous run passed: the `lint.yml` file had the ENV variable `VALIDATE_ALL_CODEBASE` set to `false` which only scans files updated in the PR:

**Comment by jesusrp98** [comment]
It works now!!

**Comment by prateekmedia** [comment]
If it will not validate the main dart code then what's the point of the linter?

**Comment by MalcolmMielle** [comment]
Validating the markdown files, CI yml files, and GitHub secret. Up to you if you think it's useful :). I'm open about it :).

**Pull request merged**
